import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SideBar from "@/components/SideBar";
import Providers from "./Providers"; // import wrapper
import PlayerComponent from "@/components/PlayerComponent";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Basic Quran App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-screen w-full bg-[#0A3D62] p-2 max-sm:p-0 flex justify-center gap-2`}
      >
        {/* <SideBar /> */}
        <div className="max-md:w-full w-[99%] h-[85vh] bg-[#2C3E50] rounded-[5px]">
          <Providers>{children}</Providers>
        </div>
      </body>
    </html>
  );
}
